// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PP_ERP.Infrastructure;

#nullable disable

namespace PP_ERP.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260330171117_InitalPurchase")]
    partial class InitalPurchase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PP_ERP.Domain.Entities.BRANCH", b =>
                {
                    b.Property<int>("BRANCH_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BRANCH_ID"));

                    b.Property<string>("BRANCH_CODE")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BRANCH_NAME")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("COMMENT")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("COMPANY_ID")
                        .HasColumnType("int");

                    b.Property<int>("CREATED_BY_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CREATED_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("EMAIL")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FACEBOOK")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("bit");

                    b.Property<bool>("IS_DELETE")
                        .HasColumnType("bit");

                    b.Property<bool>("IS_HEADQUARTER")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LAST_UPDATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<int>("LAST_UPDATE_ID")
                        .HasColumnType("int");

                    b.Property<string>("LINE")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PHONE")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ROW_UN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.HasKey("BRANCH_ID");

                    b.HasIndex("COMPANY_ID");

                    b.ToTable("BRANCH", (string)null);
                });

            modelBuilder.Entity("PP_ERP.Domain.Entities.COMPANY", b =>
                {
                    b.Property<int>("COMPANY_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("COMPANY_ID"));

                    b.Property<string>("COMMENT")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("COMPANY_CODE")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("COMPANY_NAME")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("CREATED_BY_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CREATED_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("EMAIL")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FACEBOOK")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FAX")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("bit");

                    b.Property<bool>("IS_DELETE")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LAST_UPDATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<int>("LAST_UPDATE_ID")
                        .HasColumnType("int");

                    b.Property<string>("LINE")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LOGO")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("PHONE")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ROW_UN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("TAX_NO")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("WEBSITE")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("COMPANY_ID");

                    b.ToTable("COMPANY", (string)null);
                });

            modelBuilder.Entity("PP_ERP.Domain.Entities.FLEX", b =>
                {
                    b.Property<int>("FLEX_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FLEX_ID"));

                    b.Property<int>("CREATED_BY_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CREATED_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("FLEX_CODE")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FLEX_NAME")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("bit");

                    b.Property<bool>("IS_DELETE")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LAST_UPDATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<int>("LAST_UPDATE_ID")
                        .HasColumnType("int");

                    b.Property<Guid>("ROW_UN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.HasKey("FLEX_ID");

                    b.HasIndex("FLEX_CODE");

                    b.ToTable("FLEX", (string)null);
                });

            modelBuilder.Entity("PP_ERP.Domain.Entities.FLEX_ITEM", b =>
                {
                    b.Property<int>("FLEX_ITEM_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FLEX_ITEM_ID"));

                    b.Property<int>("CREATED_BY_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CREATED_DATE")
                        .HasColumnType("datetime2");

                    b.Property<int>("FLEX_ID")
                        .HasColumnType("int");

                    b.Property<string>("FLEX_ITEM_CODE")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FLEX_ITEM_NAME")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("bit");

                    b.Property<bool>("IS_DELETE")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LAST_UPDATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<int>("LAST_UPDATE_ID")
                        .HasColumnType("int");

                    b.Property<Guid>("ROW_UN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.HasKey("FLEX_ITEM_ID");

                    b.HasIndex("FLEX_ID");

                    b.HasIndex("FLEX_ITEM_CODE");

                    b.ToTable("FLEX_ITEM", (string)null);
                });

            modelBuilder.Entity("PP_ERP.Domain.Entities.PURCHASE_ORDER", b =>
                {
                    b.Property<int>("PURCHASE_ORDER_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PURCHASE_ORDER_ID"));

                    b.Property<int>("BRANCH_ID")
                        .HasColumnType("int");

                    b.Property<string>("COMMENTS")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("COMPANY_ID")
                        .HasColumnType("int");

                    b.Property<int>("CREATED_BY_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CREATED_DATE")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DISCOUNT")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("DISCOUNT_FC")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("DOCUMENT_STATUS_CODE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("DOCUMENT_STATUS_ID")
                        .HasColumnType("int");

                    b.Property<string>("DOCUMENT_STATUS_NAME")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("DOCUMENT_STATUS_REASON")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<decimal>("GRAND_TOTAL")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GRAND_TOTAL_FC")
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("bit");

                    b.Property<bool>("IS_DELETE")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LAST_UPDATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<int>("LAST_UPDATE_ID")
                        .HasColumnType("int");

                    b.Property<decimal>("PRICE_AFTER_DISCOUNT")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PRICE_AFTER_DISCOUNT_FC")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PRICE_AFTER_VAT")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PRICE_AFTER_VAT_FC")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PRICE_BEFORE_VAT")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PRICE_BEFORE_VAT_BASE")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PRICE_BEFORE_VAT_FC")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("PURCHASE_ORDER_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("PURCHASE_ORDER_NO")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("REMARK")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("ROW_UN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<decimal>("SUB_TOTAL")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("SUB_TOTAL_FC")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("VAT")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("VAT_RATE")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("VENDOR_CODE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VENDOR_FULLNAME")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("VENDOR_ID")
                        .HasColumnType("int");

                    b.HasKey("PURCHASE_ORDER_ID");

                    b.HasIndex("BRANCH_ID");

                    b.HasIndex("COMPANY_ID");

                    b.HasIndex("DOCUMENT_STATUS_ID");

                    b.HasIndex("PURCHASE_ORDER_NO");

                    b.HasIndex("VENDOR_ID");

                    b.ToTable("PURCHASE_ORDER", (string)null);
                });

            modelBuilder.Entity("PP_ERP.Domain.Entities.SYS_USER", b =>
                {
                    b.Property<int>("USER_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("USER_ID"));

                    b.Property<int?>("BRANCH_ID")
                        .HasColumnType("int");

                    b.Property<string>("COMMENT")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("COMPANY_ID")
                        .HasColumnType("int");

                    b.Property<int>("CREATED_BY_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CREATED_DATE")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("bit");

                    b.Property<bool>("IS_DELETE")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LAST_UPDATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<int>("LAST_UPDATE_ID")
                        .HasColumnType("int");

                    b.Property<string>("PASSWORD")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ROW_UN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("USERNAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("USER_ID");

                    b.HasIndex("BRANCH_ID");

                    b.HasIndex("COMPANY_ID");

                    b.ToTable("SYS_USER", (string)null);
                });

            modelBuilder.Entity("PP_ERP.Domain.Entities.VENDOR", b =>
                {
                    b.Property<int>("VENDOR_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VENDOR_ID"));

                    b.Property<string>("COMMENTS")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("CREATED_BY_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CREATED_DATE")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("bit");

                    b.Property<bool>("IS_DELETE")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LAST_UPDATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<int>("LAST_UPDATE_ID")
                        .HasColumnType("int");

                    b.Property<Guid>("ROW_UN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<int?>("TITLE_ID")
                        .HasColumnType("int");

                    b.Property<string>("VENDOR_CODE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VENDOR_FULLNAME")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("VENDOR_FULLNAME_ENG")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("VENDOR_NAME")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("VENDOR_NAME_ENG")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("VENDOR_ID");

                    b.HasIndex("TITLE_ID");

                    b.HasIndex("VENDOR_CODE");

                    b.ToTable("VENDOR", (string)null);
                });

            modelBuilder.Entity("PP_ERP.Domain.Entities.BRANCH", b =>
                {
                    b.HasOne("PP_ERP.Domain.Entities.COMPANY", "COMPANY")
                        .WithMany("BRANCHES")
                        .HasForeignKey("COMPANY_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("COMPANY");
                });

            modelBuilder.Entity("PP_ERP.Domain.Entities.FLEX_ITEM", b =>
                {
                    b.HasOne("PP_ERP.Domain.Entities.FLEX", "FLEX")
                        .WithMany("FLEX_ITEMS")
                        .HasForeignKey("FLEX_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FLEX");
                });

            modelBuilder.Entity("PP_ERP.Domain.Entities.PURCHASE_ORDER", b =>
                {
                    b.HasOne("PP_ERP.Domain.Entities.BRANCH", "BRANCH")
                        .WithMany()
                        .HasForeignKey("BRANCH_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PP_ERP.Domain.Entities.COMPANY", "COMPANY")
                        .WithMany()
                        .HasForeignKey("COMPANY_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PP_ERP.Domain.Entities.FLEX_ITEM", "DOCUMENT_STATUS")
                        .WithMany()
                        .HasForeignKey("DOCUMENT_STATUS_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PP_ERP.Domain.Entities.VENDOR", "VENDOR")
                        .WithMany()
                        .HasForeignKey("VENDOR_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BRANCH");

                    b.Navigation("COMPANY");

                    b.Navigation("DOCUMENT_STATUS");

                    b.Navigation("VENDOR");
                });

            modelBuilder.Entity("PP_ERP.Domain.Entities.SYS_USER", b =>
                {
                    b.HasOne("PP_ERP.Domain.Entities.BRANCH", "BRANCH")
                        .WithMany()
                        .HasForeignKey("BRANCH_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PP_ERP.Domain.Entities.COMPANY", "COMPANY")
                        .WithMany()
                        .HasForeignKey("COMPANY_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BRANCH");

                    b.Navigation("COMPANY");
                });

            modelBuilder.Entity("PP_ERP.Domain.Entities.VENDOR", b =>
                {
                    b.HasOne("PP_ERP.Domain.Entities.FLEX_ITEM", "TITLE")
                        .WithMany()
                        .HasForeignKey("TITLE_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TITLE");
                });

            modelBuilder.Entity("PP_ERP.Domain.Entities.COMPANY", b =>
                {
                    b.Navigation("BRANCHES");
                });

            modelBuilder.Entity("PP_ERP.Domain.Entities.FLEX", b =>
                {
                    b.Navigation("FLEX_ITEMS");
                });
#pragma warning restore 612, 618
        }
    }
}
